blog/blog/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^projects/$', 'project.views.index'),
    url(r'^projects/([-_A-Za-z0-9]+)/$', 'project.views.detail'),
    url(r'^$', 'dblog.views.index'), # To be removed.
    url(r'^blog/$', 'dblog.views.blog'),
    url(r'^blog/([-_A-Za-z0-9]+)/$', 'dblog.views.blogDetail'),
    url(r'^tags/$', 'dblog.views.tags'),
    url(r'^tag/([-_A-Za-z0-9]+)/$','dblog.views.with_tag'),
    url(r'^tag/([-_A-Za-z0-9]+)/page/(d+)/$', 'dblog.views.with_tag' ),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^comments/', include('django.contrib.comments.urls')),
)

blog/dblog/models.py
from django.db import models
from tagging.fields import TagField
from tagging.models import Tag
from django.template.defaultfilters import slugify
# Create your models here.


class Article(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    pub_date = models.DateTimeField('date published', auto_now_add=True)
    content = models.TextField()
    flair = models.CharField('text formatting', max_length=50)
    tags = TagField()
    def set_tags(self, tags):
        Tag.objects.update_tags(self, tags)
    def get_tags(self):
        return Tag.objects.get_for_object(self)
    def getStub(self):
        return self.content[:300]
    def __unicode__(self):
        return self.title
    
class Comments(models.Model):
    topic = models.CharField(max_length=50)
    name = models.CharField(max_length=50)
    email = models.EmailField(max_length=254)
    pub_date = models.DateTimeField('date posted', auto_now_add=True)
    content = models.TextField()
    def __unicode__(self):
        return self.topic

templates/comments/base.html
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>{% block title %}{% endblock %}</title>
  {% block head %}{% endblock %}
</head>
<body>
  {% block content %}{% endblock %}
</body>
</html>

templates/comments/form.html
{% load bbcode %}{% load comments %}<div class="shell commentcontent">{% get_comment_form for article as form.as_li() %}<form action="{%comment_form_target %}" method="post">{% csrf_token %}{% for field in form %}{% ifequal field.name "name" %}{% if perms.dblog %}
    Logged in as {{ user.username }} (<a href="/admin/logout/">Not you?</a>). <input class="btn btn-primary" type="hidden" name="submit" value="{{user.username }}" value="Post" >{% else %}
    <div id="name">
      <label for="name-field" class="overlabel">Name</label>
      <input id="id_name" type="text" name="name" maxlength="50" tabindex="1"/>
    </div>{% endif %}{% else %}{% ifequal field.name "email" %}{% if perms.dblog %}
    <input type="hidden" name="email" value="{{ user.email }}" id="id_email" / >{% else %}
    <div id="email">
      <label for="id_email" class="overlabel">Email address</label>
      <input type="text" name="email" id="id_email" tabindex="2"/>
    </div>{% endif %}{% else %}{% ifequal field.name "honeypot" %}{% else %}{% ifequal field.name "comment" %}
    <div id="comment">
      <label for="id_comment" class="overlabel">Comment</label>
      <textarea id="id_comment" rows="3" col="60" name="comment" tabindex="3"></textarea>
    </div>{% else %}{% ifequal field.name "url" %}{% else %}
    {{ field }}{% endifequal %}{% endifequal %}{% endifequal %}{% endifequal %}{% endifequal %}{% endfor %}
      <input class="btn btn-mini btn-primary" type="submit" name="submit" value="Post">
      <input class="btn btn-mini" type="submit" name="preview" value="Preview">
  </form>
  <p>You can use basic BBCode in your comments. Try [b][/b] [i][/i] or [u][/u] around text. </p>
</div>

templates/comments/list.html
{% load bbcode %}
{% load comments %}<link href="http://dl.dropbox.com/u/93458715/list.css" rel="stylesheet" type="text/css" />
</br>{% get_comment_list for article as comment_list %}{% for comment in comment_list %}
  <div class="shell commentcontent">
    <div class="commentInfo">
        <p>Posted by: <a href="mailto:{{comment.email}}">{{comment.user_name}}</a> on {{comment.submit_date}}</p>
    </div>
      <p class="spaceman">{% bbcode comment.comment %}</p>
</div>{% endfor %}

templates/comments/posted.html
{% extends "comments/base.html" %}
{% load i18n %}

{% block title %}Redirecting... | DicaxDorcas{% endblock %}

{% block head %}<meta http-equiv="refresh" content="0,/" /> {% endblock %}

templates/comments/preview.html
{% extends "article/base.html" %}
{% load i18n %}
{% block title %}Comment Preview | DicaxDorcas{% endblock %}
{% block head %}
<link href="http://dl.dropbox.com/u/93458715/preview.css" rel="stylesheet" type="text/css" />{% endblock head %}
{% block body %}
  {% load comments %}
<div class="shell content article">
  <form action="{% comment_form_target %}" method="post">{% csrf_token %}
    {% if next %}<div><input type="hidden" name="next" value="{{ next }}" /></div>{% endif %}
    {% if form.errors %}
    <h3>{% blocktrans count counter=form.errors|length %}Please correct the error below{% plural %}Please correct the errors below{% endblocktrans %}</h3>
    {% else %}
    <h3>{% trans "Preview your comment" %}</h3>
      <blockquote>{{ comment|linebreaks }}</blockquote>
      <p>
      {% trans "and" %} <input type="submit" name="submit" class="submit-post" value="{% trans "Post your comment" %}" id="submit" /> {% trans "or make changes" %}:
      </p>
    {% endif %}
    {% for field in form %}
      {% if field.is_hidden %}
        <div>{{ field }}</div>
      {% else %}
        {% if field.errors %}{{ field.errors }}{% endif %}
        <p
          {% if field.errors %} class="error"{% endif %}
          {% ifequal field.name "honeypot" %} style="display:none;"{% endifequal %}
          {% if perms.dblog %} 
          {% ifequal field.name "name" %} style="display:none;"{% endifequal %}
          {% ifequal field.name "email" %} style="display:none;"{% endifequal %}
          {% endif %}
          {% ifequal field.name "url" %} style="display:none;"{% endifequal %}>
          {{ field.label_tag }} {{ field }}
        </p>
      {% endif %}
    {% endfor %}
    <p class="submit">
    <input type="submit" name="submit" class="btn btn-mini btn-primary" value="{% trans "Post" %}" />
    <input type="submit" name="preview" class="btn btn-mini" value="{% trans "Preview" %}" />
    </p>
  </form>
</div>
{% endblock body %}